### PR TITLE
Added retina support via highdpi in Window settings

### PR DESCRIPTION
**Pull request by dawidgorny**
Window setting `highdpi` is set to `Screen.getDevicePixelRatio()` by default.

### CODE REVIEW

**Comment by vorg** [comment]
I don't think this should be on by default as quite often is an overkill. 

```
highdpi    : window.settings.highdpi || Screen.getDevicePixelRatio()
```

We should keep `highdpi = 1`. And for higher values check if the device support it. E.g. if we request  `x2` but the device is a normal screen then we should drop back to `x1`.

Also I never found `highdpi` to be intuitive. Should we call it `pixelScale` or `pixelRatio` or `retina: true/false` ? Maybe bool is not enough as you might want to stick with `x2` even though iPhone 6 Plus supports `x3`...

**Comment by automat** [comment]
strongly agree on defaulting to 1

**Comment by dawidgorny** [comment]
ok, you are right. Lets leave it on 1 by default. So if I want my app to run in retina mode whenever available I have to set it up like:

```
settings: {
    width: 1280,
    height: 720,
    type: '3d',
    highdpi: Screen.getDevicePixelRatio()
  },
```

Beside number values, what if we support a nonnumerical value as an option, like "highest" or "native":
```
settings: {
    width: 1280,
    height: 720,
    type: '3d',
    pixelRatio: "highest"
  },
```
It would mimic usage of native pixel ratio, same as passing `Screen.getDevicePixelRatio()`.

I would go with `pixelRatio` instead of `highdpi`.

**Comment by vorg** [comment]
I would stick to `pixelRatio' and only numeric values. `highdpi: Screen.getDevicePixelRatio()` is not that much to ask for.

**Comment by dawidgorny** [comment]
I made changes to support `pixelRatio` while running in both Plask and a browser. It is set to `1` by default.

**Comment by vorg** [comment]
Will close that as retina handling and resize problems made us rethink the Window implementation Currently being implemented in https://github.com/pex-gl/pex-sys/blob/master/WindowImplBrowser.js

**Pull request closed without merging**
